export interface WorkoutRecord {
  id?: number // Auto-generated by IndexedDB
  title: string
  start_time: string
  end_time: string
  description: string
  exercise_title: string
  superset_id: string
  exercise_notes: string
  set_index: number
  set_type: string
  weight_kg: number | null
  reps: number | null
  distance_km: number | null
  duration_seconds: number | null
  rpe: number | null
}

export interface WorkoutSummary {
  title: string
  date: string
  totalSets: number
  totalReps: number
  totalVolume: number
  volumeDiff: number
  volumeDiffPercent: number
  exercises: string[]
}

export interface DailyWorkoutSummary {
  date: string
  workouts: WorkoutSummary[]
}

export interface ExerciseFilter {
  exerciseTitle: string
  selected: boolean
  workoutCount?: number // Counter of workouts where the exercise appears
  totalWorkouts?: number // Total workouts to calculate X/Y
}

export interface WorkoutFilters {
  selectedWorkouts: string[]
  exerciseFilters: Record<string, ExerciseFilter[]>
}
